const base = {
    baseUrl: 'http:localhost:8081',
    login: '/api/auth/login',
    register : '/api/auth/register',
    getUserInfo: '/api/auth/getUserInfo',
    getRingtoneList: '/api/ringtone/getRingtones',
    subscribe:'/api/ringtone/subscribe',
    cancelSubscribe:'/api/ringtone/cancelSubscribe',
    favourite:'/api/ringtone/favourite',
    cancelFavourite:'/api/ringtone/cancelFavourite',
    getAdvertisement:'/api/ad/getAdvertisement',
    getFavourites :'/api/ringtone/getFavourites',
    getSubscribes :'/api/ringtone/getSubscribes',
    getContacts:'/api/ringtone/getContactByUidAndRid',
    getGroups:'/api/group/getGroupsByUid',
    updateGroup:'/api/group/updateGroup',
    deleteGroup:'/api/group/deleteGroup',
    addGroup:'/api/group/addGroup',
    getContactByUidAndRid:'/api/ringtone/getContactByUidAndRid',
    getAllContactByGid : '/api/group/getAllContactByGid',
    addContactToGroup :'/api/group/addContactToGroup',
    deleteContactFromGroup:'/api/group/deleteContactFromGroup',
    addContact :'/api/ringtone/addContact',
    deleteContact :'/api/ringtone/deleteContact',
}
export default base;